# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/TreeDiagramGenerateGrpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/TreeDiagramGenerateGrpc.proto\x12 com.construction.management.grpc\"\x87\x01\n\x08Position\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x12\n\nemployeeId\x18\x02 \x01(\t\x12\x10\n\x08parentId\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x01(\t\x12\x15\n\rsubDepartment\x18\x07 \x01(\t\"^\n\x1eTreeDiagramGenerateGrpcRequest\x12<\n\x08position\x18\x01 \x03(\x0b\x32*.com.construction.management.grpc.Position\":\n\x1fTreeDiagramGenerateGrpcResponse\x12\x17\n\x0ftreeDiagramData\x18\x01 \x01(\x0c\x32\xd0\x02\n\x1eTreeDiagramGenerateGrpcService\x12\x8f\x01\n\x08getImage\x12@.com.construction.management.grpc.TreeDiagramGenerateGrpcRequest\x1a\x41.com.construction.management.grpc.TreeDiagramGenerateGrpcResponse\x12\x9b\x01\n\x14saveProjectWithImage\x12@.com.construction.management.grpc.TreeDiagramGenerateGrpcRequest\x1a\x41.com.construction.management.grpc.TreeDiagramGenerateGrpcResponseB>\n com.construction.management.grpcB\x18TreeDiagramGenerateProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.TreeDiagramGenerateGrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.construction.management.grpcB\030TreeDiagramGenerateProtoP\001'
  _globals['_POSITION']._serialized_start=74
  _globals['_POSITION']._serialized_end=209
  _globals['_TREEDIAGRAMGENERATEGRPCREQUEST']._serialized_start=211
  _globals['_TREEDIAGRAMGENERATEGRPCREQUEST']._serialized_end=305
  _globals['_TREEDIAGRAMGENERATEGRPCRESPONSE']._serialized_start=307
  _globals['_TREEDIAGRAMGENERATEGRPCRESPONSE']._serialized_end=365
  _globals['_TREEDIAGRAMGENERATEGRPCSERVICE']._serialized_start=368
  _globals['_TREEDIAGRAMGENERATEGRPCSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
