# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import TreeDiagramGenerateGrpc_pb2 as proto_dot_TreeDiagramGenerateGrpc__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/TreeDiagramGenerateGrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TreeDiagramGenerateGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getImage = channel.unary_unary(
                '/com.construction.management.grpc.TreeDiagramGenerateGrpcService/getImage',
                request_serializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.SerializeToString,
                response_deserializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.FromString,
                _registered_method=True)
        self.saveProjectWithImage = channel.unary_unary(
                '/com.construction.management.grpc.TreeDiagramGenerateGrpcService/saveProjectWithImage',
                request_serializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.SerializeToString,
                response_deserializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.FromString,
                _registered_method=True)


class TreeDiagramGenerateGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveProjectWithImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreeDiagramGenerateGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getImage': grpc.unary_unary_rpc_method_handler(
                    servicer.getImage,
                    request_deserializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.FromString,
                    response_serializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.SerializeToString,
            ),
            'saveProjectWithImage': grpc.unary_unary_rpc_method_handler(
                    servicer.saveProjectWithImage,
                    request_deserializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.FromString,
                    response_serializer=proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.construction.management.grpc.TreeDiagramGenerateGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.construction.management.grpc.TreeDiagramGenerateGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TreeDiagramGenerateGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.construction.management.grpc.TreeDiagramGenerateGrpcService/getImage',
            proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.SerializeToString,
            proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def saveProjectWithImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.construction.management.grpc.TreeDiagramGenerateGrpcService/saveProjectWithImage',
            proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcRequest.SerializeToString,
            proto_dot_TreeDiagramGenerateGrpc__pb2.TreeDiagramGenerateGrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
